modLoader="javafml"
loaderVersion="[43,)"
license="All Rights Reserved"
[[mods]]
modId="pickableorbs"
version="1.19.2-3.0-rc1"
displayName="Pickable Orbs"
logoFile="healthorbs.png"
credits="Pickable Orbs by The Decursio Team"
description='''
A small mod adding pickable configurable Orbs.
'''

[[dependencies.pickableorbs]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.pickableorbs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
