modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"
[[mods]]
modId="pickableorbs"
version="1.20.1-3.0.1"
displayName="Pickable Orbs"
logoFile="healthorbs.png"
credits="Pickable Orbs by The Decursio Team"
description='''
A small mod adding pickable configurable Orbs.
'''

[[dependencies.pickableorbs]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.pickableorbs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
