modLoader="javafml"
loaderVersion="[38,)"
license="All Rights Reserved"
[[mods]]
modId="pickableorbs"
version="2.3"
displayName="Pickable Orbs"
logoFile="healthorbs.png"
credits="Pickable Orbs by The Decursio Team"
description='''
A small mod adding pickable configurable Orbs.
'''

[[dependencies.pickableorbs]]
    modId="forge"
    mandatory=true
    versionRange="[38,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.pickableorbs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"
